"""nullable columns

Revision ID: 0070ae55a2b4
Revises: 9ae880ca01ad
Create Date: 2023-11-04 12:17:43.607627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0070ae55a2b4'
down_revision = '9ae880ca01ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('ear_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('farm_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('rejected_reason',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('rejected_info',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('configuration_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('configuration_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('configuration_value',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('lot', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.alter_column('order_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('drug_application',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('drug_used',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('treated_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.alter_column('treated_by',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('drug_used',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('drug_application',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('order_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('lot', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('configuration_value',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('configuration_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('configuration_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('rejected_info',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('rejected_reason',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('farm_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('ear_tag',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
