"""add roles to user

Revision ID: 2232962d9c61
Revises: 0070ae55a2b4
Create Date: 2023-12-03 18:33:20.740515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2232962d9c61'
down_revision = '0070ae55a2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.JSON(), nullable=False, default=['farmer']))
        batch_op.create_unique_constraint('pw_unique', ['password'])
        batch_op.create_unique_constraint('un_unique', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('pw_unique', type_='unique')
        batch_op.drop_constraint('un_unique', type_='unique')
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
