"""homogenous field names

Revision ID: 9ae880ca01ad
Revises: f26067921aa6
Create Date: 2023-11-03 19:00:59.380203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae880ca01ad'
down_revision = 'f26067921aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('configuration_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('configuration_value', sa.String(length=255), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('value')
        batch_op.drop_column('key')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('model_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('event_created_at')
        batch_op.drop_column('event_type')

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('value', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('configuration_value')
        batch_op.drop_column('configuration_type')
        batch_op.drop_column('key')

    # ### end Alembic commands ###
