"""initial version

Revision ID: abc43ff98623
Revises: 
Create Date: 2023-10-14 19:55:15.200133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc43ff98623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('animal_type', sa.String(length=255), nullable=True),
    sa.Column('ear_tag', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=True),
    sa.Column('born_at', sa.DateTime(), nullable=True),
    sa.Column('farm_code', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_parents',
    sa.Column('parent_id', sa.String(length=255), nullable=True),
    sa.Column('child_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_parents_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_animals',
    sa.Column('animal_id', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_animals_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=2000), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('password')
    )
    op.create_table('mobile_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('last_pull_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobile_device')
    op.drop_table('user')
    op.drop_table('group_changelog')
    op.drop_table('group_animals_changelog')
    op.drop_table('group_animals')
    op.drop_table('group')
    op.drop_table('farm')
    op.drop_table('animal_parents_changelog')
    op.drop_table('animal_parents')
    op.drop_table('animal_changelog')
    op.drop_table('animal')
    # ### end Alembic commands ###
