"""model for event&treatment&lot&configuration

Revision ID: bb50dfeb9dee
Revises: a46b272c38f1
Create Date: 2023-10-31 22:23:23.995401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb50dfeb9dee'
down_revision = 'a46b272c38f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('animal_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('model_created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lot_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment',
    sa.Column('order_no', sa.String(length=255), nullable=True),
    sa.Column('drug_application', sa.String(length=255), nullable=True),
    sa.Column('drug_used', sa.String(length=255), nullable=True),
    sa.Column('treated_by', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('treated_at', sa.DateTime(), nullable=True),
    sa.Column('resaled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_animals',
    sa.Column('animal_id', sa.String(length=255), nullable=True),
    sa.Column('treatment_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_animals_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watermelon_id', sa.String(length=255), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('action_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='changeoperationtype'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_id', sa.Text(), nullable=True))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('lot_id')

    op.drop_table('treatment_changelog')
    op.drop_table('treatment_animals_changelog')
    op.drop_table('treatment_animals')
    op.drop_table('treatment')
    op.drop_table('lot_changelog')
    op.drop_table('lot')
    op.drop_table('event_changelog')
    op.drop_table('event')
    op.drop_table('configuration_changelog')
    op.drop_table('configuration')
    # ### end Alembic commands ###
