"""refactor parent relation

Revision ID: f26067921aa6
Revises: bb50dfeb9dee
Create Date: 2023-11-02 20:25:23.074388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26067921aa6'
down_revision = 'bb50dfeb9dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal_parents')
    op.drop_table('animal_parents_changelog')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mother_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('mother_id')
        batch_op.drop_column('father_id')

    op.create_table('animal_parents_changelog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watermelon_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('farm_id', sa.INTEGER(), nullable=True),
    sa.Column('action_at', sa.DATETIME(), nullable=True),
    sa.Column('operation', sa.VARCHAR(length=6), nullable=False),
    sa.Column('old_value', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_parents',
    sa.Column('parent_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('child_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watermelon_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_changed_at', sa.DATETIME(), nullable=True),
    sa.Column('farm_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
